name: Release
on:
    push:
        tags:
            - '*'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: "riotkit-org/pgbr"
    GO_VERSION: "1.19"

jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            matrix:
                include:
                    - POSTGRES_VERSION: "15"
                    - POSTGRES_VERSION: "14"
                    - POSTGRES_VERSION: "13"
                    - POSTGRES_VERSION: "12"
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.17

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build
              run: "make dockerfile assets_build build GO_VERSION=${{ env.GO_VERSION }} POSTGRES_VERSION=${{ matrix.POSTGRES_VERSION }}"

            - name: Build docker image and push release image
              run: "make ci_rename_release_binary ci_release_snapshot ci_release POSTGRES_VERSION=${{ matrix.POSTGRES_VERSION }}"

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      .build/pgbr-linux-*
                      LICENSE
