name: Release
on:
    push:
        tags:
            - '*'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: "riotkit-org/backup-repository"
    GO_VERSION: "1.17"
    POSTGRES_VERSION: "14.0"

permissions:
    packages: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build
              run: "make dockerfile ci_build build GO_VERSION=${{ env.GO_VERSION }} POSTGRES_VERSION=${{ env.POSTGRES_VERSION }}"

            - name: Build docker image and push release image
              run: "make ci_release_snapshot ci_release"

#            - name: Release binaries to GitHub releases
#              uses: goreleaser/goreleaser-action@v2
#              with:
#                  distribution: goreleaser
#                  version: latest
#                  args: release --rm-dist
