name: Test
on:
    pull_request:
    push:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: "riotkit-org/backup-repository"
    GO_VERSION: "1.17"

permissions:
    packages: write

jobs:
    test-and-release-snapshot:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            matrix:
                include:
                    - POSTGRES_VERSION: "15"
                    - POSTGRES_VERSION: "14"
                    - POSTGRES_VERSION: "13"
                    - POSTGRES_VERSION: "12"
                    - POSTGRES_VERSION: "11"
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.17

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build
              run: "make dockerfile assets_build build ci_check_embedded_binaries GO_VERSION=${{ env.GO_VERSION }} POSTGRES_VERSION=${{ matrix.POSTGRES_VERSION }}"

            - name: Test
              run: "make test POSTGRES_VERSION=${{ matrix.POSTGRES_VERSION }}"

            - name: Build docker image and push snapshot image
              run: "make ci_release_snapshot POSTGRES_VERSION=${{ matrix.POSTGRES_VERSION }}"
              
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
